import "server-only";

import {
  containsNormalizedPhrase,
  normalizeTitleText,
} from "@/lib/server/title-retrieval/normalize";
import type {
  TitleAliasDefinition,
  TitleConceptDefinition,
  TitleConceptId,
  TitleFamilyDefinition,
  TitleRoleGroup,
} from "@/lib/server/title-retrieval/types";

export const titleFamilyCatalog: readonly TitleFamilyDefinition[] = [
  {
    id: "software_engineering",
    label: "Software Engineering",
    roleGroup: "engineering",
    anchorTitle: "software engineer",
    broadDiscoveryQueries: [
      "software engineer",
      "backend engineer",
      "frontend engineer",
      "full stack engineer",
      "platform engineer",
      "application engineer",
      "systems engineer",
      "mobile engineer",
      "ios engineer",
      "android engineer",
      "java developer",
      "member of technical staff",
    ],
    positiveKeywords: [
      "software engineer",
      "software developer",
      "backend engineer",
      "frontend engineer",
      "full stack engineer",
      "platform engineer",
      "application engineer",
      "systems engineer",
      "mobile engineer",
      "ios engineer",
      "android engineer",
      "java developer",
      "member of technical staff",
      "api engineer",
      "server engineer",
      "distributed systems",
      "web engineer",
    ],
    negativeKeywords: [
      "data engineer",
      "data scientist",
      "product manager",
      "recruiter",
      "qa engineer",
      "support engineer",
      "sales engineer",
      "solutions architect",
    ],
  },
  {
    id: "data_platform",
    label: "Data Platform",
    roleGroup: "engineering",
    anchorTitle: "data engineer",
    broadDiscoveryQueries: [
      "data engineer",
      "analytics engineer",
      "data platform engineer",
      "etl developer",
      "database engineer",
      "bi engineer",
      "data warehouse engineer",
      "big data engineer",
      "database developer",
      "data integration engineer",
    ],
    positiveKeywords: [
      "data engineer",
      "analytics engineer",
      "data platform engineer",
      "etl",
      "database engineer",
      "database developer",
      "bi engineer",
      "data warehouse",
      "big data",
      "data integration",
      "pipeline",
      "warehouse",
      "dbt",
      "spark",
      "bigquery",
      "lakehouse",
    ],
    negativeKeywords: [
      "software engineer",
      "frontend engineer",
      "product manager",
      "recruiter",
      "sales engineer",
      "support engineer",
    ],
  },
  {
    id: "data_analytics",
    label: "Data Analytics",
    roleGroup: "analysis",
    anchorTitle: "data analyst",
    broadDiscoveryQueries: [
      "data analyst",
      "business analyst",
      "product analyst",
      "business intelligence analyst",
      "reporting analyst",
      "operations analyst",
      "financial analyst",
      "marketing analyst",
      "sales analyst",
      "strategy analyst",
    ],
    positiveKeywords: [
      "data analyst",
      "business analyst",
      "product analyst",
      "business intelligence",
      "reporting analyst",
      "financial analyst",
      "marketing analyst",
      "sales analyst",
      "strategy analyst",
      "insights analyst",
      "analytics analyst",
    ],
    negativeKeywords: [
      "engineer",
      "developer",
      "architect",
      "product manager",
      "technical recruiter",
    ],
  },
  {
    id: "ai_ml_science",
    label: "AI / ML Science",
    roleGroup: "engineering",
    anchorTitle: "machine learning engineer",
    broadDiscoveryQueries: [
      "machine learning engineer",
      "ai engineer",
      "applied scientist",
      "research scientist",
      "data scientist",
      "nlp engineer",
      "computer vision engineer",
      "mlops engineer",
      "ai research engineer",
      "decision scientist",
    ],
    positiveKeywords: [
      "machine learning",
      "ai engineer",
      "artificial intelligence",
      "applied scientist",
      "research scientist",
      "data scientist",
      "nlp",
      "computer vision",
      "mlops",
      "decision scientist",
      "llm",
      "generative ai",
    ],
    negativeKeywords: [
      "product manager",
      "recruiter",
      "technical writer",
      "support engineer",
      "sales engineer",
    ],
  },
  {
    id: "product",
    label: "Product",
    roleGroup: "management",
    anchorTitle: "product manager",
    broadDiscoveryQueries: [
      "product manager",
      "technical product manager",
      "senior product manager",
      "associate product manager",
      "product owner",
      "growth product manager",
      "platform product manager",
      "apm",
    ],
    positiveKeywords: [
      "product manager",
      "technical product manager",
      "associate product manager",
      "product owner",
      "growth product manager",
      "platform product manager",
      "apm",
    ],
    negativeKeywords: [
      "program manager",
      "project manager",
      "recruiter",
      "sales engineer",
    ],
  },
  {
    id: "cloud_devops_security",
    label: "Cloud / DevOps / Security",
    roleGroup: "engineering",
    anchorTitle: "devops engineer",
    broadDiscoveryQueries: [
      "devops engineer",
      "site reliability engineer",
      "cloud engineer",
      "infrastructure engineer",
      "reliability engineer",
      "security engineer",
      "cloud security engineer",
      "network engineer",
      "systems administrator",
      "devsecops engineer",
    ],
    positiveKeywords: [
      "devops",
      "site reliability",
      "sre",
      "cloud engineer",
      "infrastructure engineer",
      "reliability engineer",
      "security engineer",
      "cloud security engineer",
      "network engineer",
      "systems administrator",
      "devsecops",
    ],
    negativeKeywords: [
      "product manager",
      "recruiter",
      "sales engineer",
      "qa engineer",
    ],
  },
  {
    id: "qa_support_it",
    label: "QA / Support / IT",
    roleGroup: "quality",
    anchorTitle: "qa engineer",
    broadDiscoveryQueries: [
      "qa engineer",
      "test engineer",
      "sdet",
      "automation engineer",
      "support engineer",
      "technical support engineer",
      "it support specialist",
      "help desk analyst",
      "implementation engineer",
      "solutions support engineer",
    ],
    positiveKeywords: [
      "qa engineer",
      "quality assurance",
      "test engineer",
      "sdet",
      "automation engineer",
      "support engineer",
      "technical support",
      "help desk",
      "it support",
      "implementation engineer",
      "solutions support engineer",
    ],
    negativeKeywords: [
      "product manager",
      "recruiter",
      "sales engineer",
      "solutions architect",
    ],
  },
  {
    id: "architecture_solutions",
    label: "Architecture / Solutions",
    roleGroup: "solutions",
    anchorTitle: "solutions architect",
    broadDiscoveryQueries: [
      "solution architect",
      "solutions architect",
      "solutions architecture",
      "enterprise architect",
      "cloud architect",
      "technical architect",
      "salesforce architect",
      "presales engineer",
      "sales engineer",
      "solutions engineer",
      "implementation consultant",
    ],
    positiveKeywords: [
      "solution architect",
      "solutions architect",
      "solutions architecture",
      "enterprise architect",
      "cloud architect",
      "technical architect",
      "salesforce architect",
      "presales engineer",
      "pre sales engineer",
      "sales engineer",
      "solutions engineer",
      "implementation consultant",
    ],
    negativeKeywords: [
      "qa engineer",
      "recruiter",
      "data analyst",
      "technical writer",
    ],
  },
  {
    id: "design_content_marketing",
    label: "Design / Content / Marketing",
    roleGroup: "design",
    anchorTitle: "product designer",
    broadDiscoveryQueries: [
      "ux designer",
      "ui designer",
      "product designer",
      "ux researcher",
      "graphic designer",
      "content strategist",
      "technical writer",
      "digital marketing manager",
      "marketing manager",
      "seo specialist",
    ],
    positiveKeywords: [
      "ux designer",
      "ui designer",
      "product designer",
      "ux researcher",
      "graphic designer",
      "content strategist",
      "technical writer",
      "marketing manager",
      "digital marketing",
      "seo specialist",
    ],
    negativeKeywords: [
      "software engineer",
      "data engineer",
      "recruiter",
      "sales engineer",
    ],
  },
  {
    id: "business_operations_people",
    label: "Business / Operations / People",
    roleGroup: "operations",
    anchorTitle: "operations manager",
    broadDiscoveryQueries: [
      "recruiter",
      "technical recruiter",
      "talent acquisition specialist",
      "customer success manager",
      "account manager",
      "operations manager",
      "program manager",
      "technical program manager",
      "project manager",
      "supply chain analyst",
      "hr generalist",
      "finance manager",
      "revenue operations analyst",
    ],
    positiveKeywords: [
      "recruiter",
      "technical recruiter",
      "talent acquisition",
      "customer success",
      "account manager",
      "operations manager",
      "program manager",
      "project manager",
      "supply chain analyst",
      "hr generalist",
      "finance manager",
      "revenue operations",
    ],
    negativeKeywords: [
      "software engineer",
      "data engineer",
      "ai engineer",
      "sales engineer",
      "technical writer",
    ],
  },
] satisfies readonly TitleFamilyDefinition[];

export const titleConceptCatalog: readonly TitleConceptDefinition[] = [
  {
    id: "software_engineer",
    family: "software_engineering",
    canonicalTitle: "software engineer",
    aliases: [
      "software developer",
      "software development engineer",
      "software engineering",
      "application engineer",
      "application developer",
      "applications engineer",
      "applications developer",
      "application software engineer",
      "web application developer",
    ],
    abbreviations: ["swe", "sde"],
    tokenSynonyms: [
      ["software", "application", "applications"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: [
      "backend_engineer",
      "frontend_engineer",
      "full_stack_engineer",
      "platform_engineer",
      "mobile_engineer",
      "java_developer",
      "member_of_technical_staff",
    ],
    broadDiscoveryQueries: [
      "software engineer",
      "software developer",
      "software development engineer",
      "application engineer",
      "application developer",
      "backend engineer",
      "frontend engineer",
      "full stack engineer",
      "platform engineer",
      "mobile engineer",
      "java developer",
      "member of technical staff",
      "swe",
    ],
  },
  {
    id: "backend_engineer",
    family: "software_engineering",
    canonicalTitle: "backend engineer",
    aliases: [
      "backend developer",
      "back end engineer",
      "back end developer",
      "api engineer",
      "api developer",
      "server engineer",
      "server side engineer",
      "backend software engineer",
    ],
    tokenSynonyms: [
      ["backend", "server", "api"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: [
      "software_engineer",
      "full_stack_engineer",
      "platform_engineer",
    ],
    broadDiscoveryQueries: [
      "backend engineer",
      "backend developer",
      "api engineer",
      "api developer",
      "server engineer",
      "software engineer",
    ],
  },
  {
    id: "frontend_engineer",
    family: "software_engineering",
    canonicalTitle: "frontend engineer",
    aliases: [
      "frontend developer",
      "front end engineer",
      "front end developer",
      "ui engineer",
      "web engineer",
      "frontend software engineer",
    ],
    tokenSynonyms: [
      ["frontend", "ui", "web"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: [
      "software_engineer",
      "full_stack_engineer",
      "mobile_engineer",
    ],
    broadDiscoveryQueries: [
      "frontend engineer",
      "frontend developer",
      "ui engineer",
      "web engineer",
      "software engineer",
    ],
  },
  {
    id: "full_stack_engineer",
    family: "software_engineering",
    canonicalTitle: "full stack engineer",
    aliases: [
      "fullstack engineer",
      "full stack developer",
      "fullstack developer",
      "full stack software engineer",
    ],
    tokenSynonyms: [
      ["full stack", "fullstack"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: [
      "software_engineer",
      "backend_engineer",
      "frontend_engineer",
    ],
    broadDiscoveryQueries: [
      "full stack engineer",
      "fullstack engineer",
      "full stack developer",
      "backend engineer",
      "frontend engineer",
      "software engineer",
    ],
  },
  {
    id: "platform_engineer",
    family: "software_engineering",
    canonicalTitle: "platform engineer",
    aliases: [
      "platform developer",
      "systems engineer",
      "distributed systems engineer",
      "service engineer",
    ],
    tokenSynonyms: [
      ["platform", "systems", "distributed", "service"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: [
      "software_engineer",
      "backend_engineer",
      "member_of_technical_staff",
    ],
    broadDiscoveryQueries: [
      "platform engineer",
      "platform developer",
      "systems engineer",
      "distributed systems engineer",
      "software engineer",
    ],
  },
  {
    id: "mobile_engineer",
    family: "software_engineering",
    canonicalTitle: "mobile engineer",
    aliases: [
      "mobile developer",
      "ios engineer",
      "android engineer",
      "ios developer",
      "android developer",
    ],
    tokenSynonyms: [
      ["mobile", "ios", "android"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: ["software_engineer", "frontend_engineer"],
    broadDiscoveryQueries: [
      "mobile engineer",
      "mobile developer",
      "ios engineer",
      "android engineer",
      "software engineer",
    ],
  },
  {
    id: "java_developer",
    family: "software_engineering",
    canonicalTitle: "java developer",
    aliases: ["java engineer", "jvm engineer", "java software engineer"],
    tokenSynonyms: [
      ["java", "jvm"],
      ["developer", "engineer"],
    ],
    adjacentConceptIds: ["software_engineer", "backend_engineer"],
    broadDiscoveryQueries: [
      "java developer",
      "java engineer",
      "backend engineer",
      "software engineer",
    ],
  },
  {
    id: "member_of_technical_staff",
    family: "software_engineering",
    canonicalTitle: "member of technical staff",
    aliases: ["member technical staff", "technical staff member"],
    abbreviations: ["mts"],
    tokenSynonyms: [
      ["member of technical staff", "mts"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: [
      "software_engineer",
      "backend_engineer",
      "platform_engineer",
    ],
    broadDiscoveryQueries: [
      "member of technical staff",
      "mts",
      "software engineer",
      "backend engineer",
      "platform engineer",
    ],
  },
  {
    id: "data_engineer",
    family: "data_platform",
    canonicalTitle: "data engineer",
    aliases: [
      "etl developer",
      "etl engineer",
      "big data engineer",
      "data integration engineer",
      "data pipeline engineer",
      "software engineer data engineering",
    ],
    tokenSynonyms: [
      ["data", "big data", "data pipeline", "data integration"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: ["analytics_engineer", "data_platform_engineer"],
    broadDiscoveryQueries: [
      "data engineer",
      "etl developer",
      "big data engineer",
      "data integration engineer",
      "analytics engineer",
      "data platform engineer",
    ],
    negativeConceptIds: [
      "software_engineer",
      "backend_engineer",
      "frontend_engineer",
      "product_manager",
    ],
    negativeKeywords: ["frontend", "backend", "mobile", "sales engineer"],
  },
  {
    id: "analytics_engineer",
    family: "data_platform",
    canonicalTitle: "analytics engineer",
    aliases: ["bi engineer", "business intelligence engineer", "analytics developer"],
    tokenSynonyms: [
      ["analytics", "business intelligence", "bi"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: ["data_engineer", "data_platform_engineer"],
    broadDiscoveryQueries: [
      "analytics engineer",
      "bi engineer",
      "data engineer",
      "data platform engineer",
    ],
    negativeConceptIds: ["software_engineer", "frontend_engineer"],
    negativeKeywords: ["frontend", "mobile", "sales engineer"],
  },
  {
    id: "data_platform_engineer",
    family: "data_platform",
    canonicalTitle: "data platform engineer",
    aliases: [
      "data warehouse engineer",
      "database engineer",
      "database developer",
      "data platform developer",
      "data infrastructure engineer",
    ],
    tokenSynonyms: [
      ["data platform", "data warehouse", "database", "data infrastructure"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: ["data_engineer", "analytics_engineer"],
    broadDiscoveryQueries: [
      "data platform engineer",
      "data warehouse engineer",
      "database engineer",
      "database developer",
      "data engineer",
    ],
    negativeConceptIds: ["software_engineer", "platform_engineer"],
    negativeKeywords: ["frontend", "mobile", "support engineer"],
  },
  {
    id: "data_analyst",
    family: "data_analytics",
    canonicalTitle: "data analyst",
    roleGroup: "analysis",
    aliases: [
      "analytics analyst",
      "product analyst",
      "business intelligence analyst",
      "reporting analyst",
      "insights analyst",
      "marketing analyst",
      "sales analyst",
      "strategy analyst",
    ],
    abbreviations: ["bi analyst"],
    tokenSynonyms: [
      ["data", "analytics", "insights", "reporting"],
      ["business intelligence", "bi"],
      ["analyst", "scientist"],
    ],
    adjacentConceptIds: ["business_analyst", "financial_analyst"],
    broadDiscoveryQueries: [
      "data analyst",
      "product analyst",
      "business intelligence analyst",
      "reporting analyst",
      "marketing analyst",
      "sales analyst",
      "strategy analyst",
      "business analyst",
      "financial analyst",
      "bi analyst",
    ],
  },
  {
    id: "business_analyst",
    family: "data_analytics",
    canonicalTitle: "business analyst",
    roleGroup: "analysis",
    aliases: [
      "business systems analyst",
      "systems analyst",
      "functional analyst",
      "business process analyst",
    ],
    tokenSynonyms: [
      ["business", "functional", "systems", "process"],
      ["analyst", "consultant"],
    ],
    adjacentConceptIds: ["data_analyst", "operations_analyst"],
    broadDiscoveryQueries: [
      "business analyst",
      "business systems analyst",
      "systems analyst",
      "business process analyst",
      "data analyst",
      "operations analyst",
    ],
  },
  {
    id: "operations_analyst",
    family: "data_analytics",
    canonicalTitle: "operations analyst",
    roleGroup: "analysis",
    aliases: ["revenue operations analyst", "supply chain analyst", "ops analyst"],
    tokenSynonyms: [
      ["operations", "revenue operations", "supply chain", "ops"],
      ["analyst", "specialist"],
    ],
    adjacentConceptIds: ["business_analyst", "financial_analyst"],
    broadDiscoveryQueries: [
      "operations analyst",
      "revenue operations analyst",
      "supply chain analyst",
      "business analyst",
      "financial analyst",
    ],
    negativeKeywords: ["data engineer", "software engineer"],
  },
  {
    id: "financial_analyst",
    family: "data_analytics",
    canonicalTitle: "financial analyst",
    roleGroup: "analysis",
    aliases: ["finance analyst"],
    tokenSynonyms: [
      ["financial", "finance"],
      ["analyst", "manager"],
    ],
    adjacentConceptIds: ["data_analyst", "operations_analyst"],
    broadDiscoveryQueries: [
      "financial analyst",
      "finance analyst",
      "data analyst",
      "operations analyst",
    ],
  },
  {
    id: "machine_learning_engineer",
    family: "ai_ml_science",
    canonicalTitle: "machine learning engineer",
    aliases: ["ml engineer", "machine learning developer"],
    tokenSynonyms: [
      ["machine learning", "ml"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: [
      "ai_engineer",
      "mlops_engineer",
      "data_scientist",
      "applied_scientist",
    ],
    broadDiscoveryQueries: [
      "machine learning engineer",
      "ml engineer",
      "ai engineer",
      "mlops engineer",
      "data scientist",
      "applied scientist",
    ],
  },
  {
    id: "ai_engineer",
    family: "ai_ml_science",
    canonicalTitle: "ai engineer",
    aliases: [
      "artificial intelligence engineer",
      "ai research engineer",
      "nlp engineer",
      "computer vision engineer",
    ],
    tokenSynonyms: [
      ["ai", "artificial intelligence", "nlp", "computer vision"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: [
      "machine_learning_engineer",
      "applied_scientist",
      "research_scientist",
      "data_scientist",
    ],
    broadDiscoveryQueries: [
      "ai engineer",
      "artificial intelligence engineer",
      "nlp engineer",
      "computer vision engineer",
      "machine learning engineer",
      "applied scientist",
      "research scientist",
    ],
  },
  {
    id: "applied_scientist",
    family: "ai_ml_science",
    canonicalTitle: "applied scientist",
    roleGroup: "analysis",
    aliases: ["applied ai scientist"],
    tokenSynonyms: [
      ["applied", "production"],
      ["scientist", "researcher"],
    ],
    adjacentConceptIds: [
      "research_scientist",
      "data_scientist",
      "ai_engineer",
      "machine_learning_engineer",
    ],
    broadDiscoveryQueries: [
      "applied scientist",
      "research scientist",
      "data scientist",
      "ai engineer",
      "machine learning engineer",
    ],
  },
  {
    id: "research_scientist",
    family: "ai_ml_science",
    canonicalTitle: "research scientist",
    roleGroup: "analysis",
    aliases: ["ai research scientist"],
    tokenSynonyms: [
      ["research", "experimentation"],
      ["scientist", "researcher"],
    ],
    adjacentConceptIds: [
      "applied_scientist",
      "data_scientist",
      "ai_engineer",
    ],
    broadDiscoveryQueries: [
      "research scientist",
      "applied scientist",
      "data scientist",
      "ai engineer",
    ],
  },
  {
    id: "data_scientist",
    family: "ai_ml_science",
    canonicalTitle: "data scientist",
    roleGroup: "analysis",
    aliases: ["decision scientist"],
    tokenSynonyms: [
      ["data", "decision"],
      ["scientist", "analyst"],
    ],
    adjacentConceptIds: [
      "applied_scientist",
      "research_scientist",
      "machine_learning_engineer",
      "ai_engineer",
    ],
    broadDiscoveryQueries: [
      "data scientist",
      "decision scientist",
      "applied scientist",
      "research scientist",
      "machine learning engineer",
    ],
  },
  {
    id: "mlops_engineer",
    family: "ai_ml_science",
    canonicalTitle: "mlops engineer",
    aliases: ["ml ops engineer", "machine learning operations engineer"],
    tokenSynonyms: [
      ["mlops", "machine learning operations"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: ["machine_learning_engineer", "ai_engineer"],
    broadDiscoveryQueries: [
      "mlops engineer",
      "machine learning engineer",
      "ai engineer",
    ],
  },
  {
    id: "product_manager",
    family: "product",
    canonicalTitle: "product manager",
    roleGroup: "management",
    aliases: [
      "product owner",
      "product lead",
      "product mgr",
      "senior product manager",
    ],
    tokenSynonyms: [
      ["product", "platform", "growth"],
      ["manager", "owner", "lead"],
    ],
    adjacentConceptIds: [
      "technical_product_manager",
      "associate_product_manager",
      "growth_product_manager",
    ],
    broadDiscoveryQueries: [
      "product manager",
      "product owner",
      "senior product manager",
      "technical product manager",
      "associate product manager",
      "growth product manager",
      "apm",
    ],
    negativeConceptIds: ["program_manager", "technical_program_manager"],
  },
  {
    id: "technical_product_manager",
    family: "product",
    canonicalTitle: "technical product manager",
    roleGroup: "management",
    aliases: ["platform product manager", "technical product owner", "technical product mgr"],
    tokenSynonyms: [
      ["technical", "platform"],
      ["product", "pm"],
      ["manager", "owner"],
    ],
    adjacentConceptIds: [
      "product_manager",
      "associate_product_manager",
      "growth_product_manager",
    ],
    broadDiscoveryQueries: [
      "technical product manager",
      "platform product manager",
      "product manager",
      "growth product manager",
    ],
    negativeConceptIds: ["program_manager", "technical_program_manager"],
  },
  {
    id: "associate_product_manager",
    family: "product",
    canonicalTitle: "associate product manager",
    roleGroup: "management",
    abbreviations: ["apm"],
    tokenSynonyms: [
      ["associate", "apm"],
      ["product", "pm"],
      ["manager", "owner"],
    ],
    adjacentConceptIds: [
      "product_manager",
      "technical_product_manager",
      "growth_product_manager",
    ],
    broadDiscoveryQueries: [
      "associate product manager",
      "apm",
      "product manager",
      "technical product manager",
    ],
  },
  {
    id: "growth_product_manager",
    family: "product",
    canonicalTitle: "growth product manager",
    roleGroup: "management",
    aliases: ["growth pm"],
    tokenSynonyms: [
      ["growth", "product"],
      ["manager", "pm"],
    ],
    adjacentConceptIds: [
      "product_manager",
      "technical_product_manager",
      "associate_product_manager",
    ],
    broadDiscoveryQueries: [
      "growth product manager",
      "growth pm",
      "product manager",
      "technical product manager",
    ],
  },
  {
    id: "program_manager",
    family: "business_operations_people",
    canonicalTitle: "program manager",
    roleGroup: "management",
    aliases: ["project manager", "program lead", "program management"],
    tokenSynonyms: [
      ["program", "project"],
      ["manager", "lead"],
    ],
    adjacentConceptIds: ["technical_program_manager", "operations_manager"],
    broadDiscoveryQueries: [
      "program manager",
      "project manager",
      "technical program manager",
      "operations manager",
    ],
    negativeConceptIds: ["product_manager", "technical_product_manager"],
  },
  {
    id: "technical_program_manager",
    family: "business_operations_people",
    canonicalTitle: "technical program manager",
    roleGroup: "management",
    aliases: ["tpm program manager"],
    abbreviations: ["tpm"],
    adjacentConceptIds: ["program_manager", "operations_manager"],
    broadDiscoveryQueries: [
      "technical program manager",
      "tpm",
      "program manager",
      "project manager",
    ],
    negativeConceptIds: ["product_manager", "technical_product_manager"],
  },
  {
    id: "devops_engineer",
    family: "cloud_devops_security",
    canonicalTitle: "devops engineer",
    aliases: [
      "site reliability engineer",
      "reliability engineer",
      "devsecops engineer",
    ],
    abbreviations: ["sre"],
    tokenSynonyms: [
      ["devops", "site reliability", "sre", "devsecops", "reliability"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: ["cloud_engineer", "security_engineer"],
    broadDiscoveryQueries: [
      "devops engineer",
      "site reliability engineer",
      "reliability engineer",
      "devsecops engineer",
      "cloud engineer",
      "security engineer",
    ],
  },
  {
    id: "cloud_engineer",
    family: "cloud_devops_security",
    canonicalTitle: "cloud engineer",
    aliases: [
      "infrastructure engineer",
      "network engineer",
      "systems administrator",
    ],
    tokenSynonyms: [
      ["cloud", "infrastructure", "network", "systems"],
      ["engineer", "administrator"],
    ],
    adjacentConceptIds: ["devops_engineer", "security_engineer", "cloud_architect"],
    broadDiscoveryQueries: [
      "cloud engineer",
      "infrastructure engineer",
      "network engineer",
      "systems administrator",
      "devops engineer",
      "cloud architect",
    ],
  },
  {
    id: "security_engineer",
    family: "cloud_devops_security",
    canonicalTitle: "security engineer",
    aliases: ["cloud security engineer"],
    tokenSynonyms: [
      ["security", "cloud security"],
      ["engineer", "analyst"],
    ],
    adjacentConceptIds: ["devops_engineer", "cloud_engineer"],
    broadDiscoveryQueries: [
      "security engineer",
      "cloud security engineer",
      "devops engineer",
      "cloud engineer",
    ],
  },
  {
    id: "qa_engineer",
    family: "qa_support_it",
    canonicalTitle: "qa engineer",
    roleGroup: "quality",
    aliases: [
      "quality assurance engineer",
      "quality engineer",
      "automation engineer",
      "qa analyst",
    ],
    tokenSynonyms: [
      ["qa", "quality", "quality assurance", "automation"],
      ["engineer", "analyst"],
    ],
    adjacentConceptIds: ["test_engineer", "software_engineer_in_test"],
    broadDiscoveryQueries: [
      "qa engineer",
      "quality assurance engineer",
      "automation engineer",
      "test engineer",
      "software engineer in test",
      "sdet",
    ],
    negativeConceptIds: ["software_engineer", "sales_engineer"],
  },
  {
    id: "test_engineer",
    family: "qa_support_it",
    canonicalTitle: "test engineer",
    roleGroup: "quality",
    aliases: ["validation engineer", "software tester"],
    tokenSynonyms: [
      ["test", "testing", "validation", "quality"],
      ["engineer", "tester"],
    ],
    adjacentConceptIds: ["qa_engineer", "software_engineer_in_test"],
    broadDiscoveryQueries: [
      "test engineer",
      "qa engineer",
      "software engineer in test",
      "sdet",
    ],
  },
  {
    id: "software_engineer_in_test",
    family: "qa_support_it",
    canonicalTitle: "software engineer in test",
    roleGroup: "quality",
    aliases: [
      "software developer in test",
      "software development engineer in test",
    ],
    abbreviations: ["sdet"],
    tokenSynonyms: [
      ["software engineer in test", "software developer in test", "sdet"],
      ["engineer", "developer"],
    ],
    adjacentConceptIds: ["qa_engineer", "test_engineer"],
    broadDiscoveryQueries: [
      "software engineer in test",
      "software developer in test",
      "sdet",
      "qa engineer",
      "test engineer",
    ],
  },
  {
    id: "support_engineer",
    family: "qa_support_it",
    canonicalTitle: "support engineer",
    roleGroup: "support",
    aliases: [
      "technical support engineer",
      "solutions support engineer",
      "implementation engineer",
      "application support engineer",
    ],
    tokenSynonyms: [
      ["support", "technical support", "solutions support", "implementation"],
      ["engineer", "specialist"],
    ],
    adjacentConceptIds: ["it_support_specialist"],
    broadDiscoveryQueries: [
      "support engineer",
      "technical support engineer",
      "solutions support engineer",
      "implementation engineer",
      "it support specialist",
    ],
    negativeConceptIds: ["software_engineer", "sales_engineer"],
  },
  {
    id: "it_support_specialist",
    family: "qa_support_it",
    canonicalTitle: "it support specialist",
    roleGroup: "support",
    aliases: ["help desk analyst", "help desk specialist"],
    tokenSynonyms: [
      ["it support", "help desk", "desktop support"],
      ["specialist", "analyst"],
    ],
    adjacentConceptIds: ["support_engineer"],
    broadDiscoveryQueries: [
      "it support specialist",
      "help desk analyst",
      "support engineer",
    ],
  },
  {
    id: "solutions_architect",
    family: "architecture_solutions",
    canonicalTitle: "solutions architect",
    roleGroup: "solutions",
    aliases: [
      "solution architect",
      "solutions architecture",
      "solution architecture",
    ],
    tokenSynonyms: [
      ["solution", "solutions"],
      ["architect", "architecture"],
    ],
    adjacentConceptIds: [
      "enterprise_architect",
      "cloud_architect",
      "solutions_engineer",
      "implementation_consultant",
    ],
    broadDiscoveryQueries: [
      "solutions architect",
      "solution architect",
      "solutions architecture",
      "enterprise architect",
      "cloud architect",
      "technical architect",
      "solutions engineer",
    ],
  },
  {
    id: "enterprise_architect",
    family: "architecture_solutions",
    canonicalTitle: "enterprise architect",
    roleGroup: "solutions",
    aliases: ["technical architect", "salesforce architect"],
    tokenSynonyms: [
      ["enterprise", "technical", "salesforce"],
      ["architect", "architecture"],
    ],
    adjacentConceptIds: ["solutions_architect", "cloud_architect"],
    broadDiscoveryQueries: [
      "enterprise architect",
      "technical architect",
      "salesforce architect",
      "solutions architect",
      "cloud architect",
    ],
  },
  {
    id: "cloud_architect",
    family: "architecture_solutions",
    canonicalTitle: "cloud architect",
    roleGroup: "solutions",
    aliases: [],
    tokenSynonyms: [
      ["cloud", "infrastructure"],
      ["architect", "architecture"],
    ],
    adjacentConceptIds: ["solutions_architect", "enterprise_architect", "cloud_engineer"],
    broadDiscoveryQueries: [
      "cloud architect",
      "solutions architect",
      "enterprise architect",
      "cloud engineer",
    ],
  },
  {
    id: "solutions_engineer",
    family: "architecture_solutions",
    canonicalTitle: "solutions engineer",
    roleGroup: "solutions",
    aliases: [
      "sales engineer",
      "presales engineer",
      "pre sales engineer",
      "solutions consultant",
    ],
    tokenSynonyms: [
      ["solutions", "sales", "presales", "pre sales"],
      ["engineer", "consultant"],
    ],
    adjacentConceptIds: [
      "solutions_architect",
      "implementation_consultant",
    ],
    broadDiscoveryQueries: [
      "solutions engineer",
      "sales engineer",
      "presales engineer",
      "solutions architect",
      "implementation consultant",
    ],
    negativeConceptIds: ["software_engineer"],
  },
  {
    id: "implementation_consultant",
    family: "architecture_solutions",
    canonicalTitle: "implementation consultant",
    roleGroup: "solutions",
    aliases: [],
    tokenSynonyms: [
      ["implementation", "deployment"],
      ["consultant", "specialist"],
    ],
    adjacentConceptIds: ["solutions_architect", "solutions_engineer"],
    broadDiscoveryQueries: [
      "implementation consultant",
      "solutions engineer",
      "solutions architect",
    ],
  },
  {
    id: "technical_writer",
    family: "design_content_marketing",
    canonicalTitle: "technical writer",
    roleGroup: "writing",
    aliases: [
      "documentation writer",
      "documentation specialist",
      "api writer",
      "content strategist",
      "docs writer",
    ],
    tokenSynonyms: [
      ["technical", "documentation", "content", "api"],
      ["writer", "specialist"],
    ],
    adjacentConceptIds: ["marketing_manager"],
    broadDiscoveryQueries: [
      "technical writer",
      "documentation writer",
      "documentation specialist",
      "content strategist",
      "api writer",
    ],
  },
  {
    id: "product_designer",
    family: "design_content_marketing",
    canonicalTitle: "product designer",
    roleGroup: "design",
    aliases: ["ux designer", "ui designer", "graphic designer"],
    tokenSynonyms: [
      ["product", "ux", "ui", "graphic"],
      ["designer", "design"],
    ],
    adjacentConceptIds: ["ux_researcher"],
    broadDiscoveryQueries: [
      "product designer",
      "ux designer",
      "ui designer",
      "graphic designer",
      "ux researcher",
    ],
  },
  {
    id: "ux_researcher",
    family: "design_content_marketing",
    canonicalTitle: "ux researcher",
    roleGroup: "design",
    aliases: [],
    tokenSynonyms: [
      ["ux", "user"],
      ["researcher", "analyst"],
    ],
    adjacentConceptIds: ["product_designer"],
    broadDiscoveryQueries: [
      "ux researcher",
      "product designer",
      "ux designer",
    ],
  },
  {
    id: "marketing_manager",
    family: "design_content_marketing",
    canonicalTitle: "marketing manager",
    roleGroup: "management",
    aliases: ["digital marketing manager", "seo specialist"],
    tokenSynonyms: [
      ["marketing", "digital marketing", "seo"],
      ["manager", "specialist"],
    ],
    adjacentConceptIds: ["technical_writer"],
    broadDiscoveryQueries: [
      "marketing manager",
      "digital marketing manager",
      "seo specialist",
      "content strategist",
    ],
  },
  {
    id: "recruiter",
    family: "business_operations_people",
    canonicalTitle: "recruiter",
    roleGroup: "recruiting",
    aliases: ["talent acquisition specialist", "talent acquisition partner", "sourcer"],
    tokenSynonyms: [
      ["recruiter", "talent acquisition", "sourcer"],
      ["partner", "specialist"],
    ],
    adjacentConceptIds: ["technical_recruiter"],
    broadDiscoveryQueries: [
      "recruiter",
      "technical recruiter",
      "talent acquisition specialist",
      "talent acquisition partner",
      "sourcer",
    ],
  },
  {
    id: "technical_recruiter",
    family: "business_operations_people",
    canonicalTitle: "technical recruiter",
    roleGroup: "recruiting",
    aliases: ["engineering recruiter", "tech recruiter"],
    tokenSynonyms: [
      ["technical", "engineering", "tech"],
      ["recruiter", "sourcer"],
    ],
    adjacentConceptIds: ["recruiter"],
    broadDiscoveryQueries: [
      "technical recruiter",
      "recruiter",
      "engineering recruiter",
      "talent acquisition specialist",
    ],
  },
  {
    id: "customer_success_manager",
    family: "business_operations_people",
    canonicalTitle: "customer success manager",
    roleGroup: "management",
    aliases: ["account manager"],
    tokenSynonyms: [
      ["customer success", "account"],
      ["manager", "lead"],
    ],
    adjacentConceptIds: ["operations_manager"],
    broadDiscoveryQueries: [
      "customer success manager",
      "account manager",
      "operations manager",
    ],
  },
  {
    id: "operations_manager",
    family: "business_operations_people",
    canonicalTitle: "operations manager",
    roleGroup: "management",
    aliases: ["business operations manager"],
    tokenSynonyms: [
      ["operations", "business operations"],
      ["manager", "coordinator"],
    ],
    adjacentConceptIds: [
      "program_manager",
      "technical_program_manager",
      "customer_success_manager",
      "finance_manager",
    ],
    broadDiscoveryQueries: [
      "operations manager",
      "business operations manager",
      "program manager",
      "technical program manager",
      "finance manager",
    ],
  },
  {
    id: "hr_generalist",
    family: "business_operations_people",
    canonicalTitle: "hr generalist",
    roleGroup: "operations",
    aliases: [],
    tokenSynonyms: [
      ["hr", "human resources", "people"],
      ["generalist", "specialist"],
    ],
    adjacentConceptIds: ["recruiter"],
    broadDiscoveryQueries: [
      "hr generalist",
      "recruiter",
      "talent acquisition specialist",
    ],
  },
  {
    id: "finance_manager",
    family: "business_operations_people",
    canonicalTitle: "finance manager",
    roleGroup: "management",
    aliases: [],
    tokenSynonyms: [
      ["finance", "financial"],
      ["manager", "lead"],
    ],
    adjacentConceptIds: ["operations_manager"],
    broadDiscoveryQueries: [
      "finance manager",
      "financial analyst",
      "operations manager",
    ],
  },
] satisfies readonly TitleConceptDefinition[];

const roleGroupByFamily = new Map<string, TitleRoleGroup>(
  titleFamilyCatalog.map((family) => [family.id, family.roleGroup] as const),
);

const titleConceptById = new Map<TitleConceptId, TitleConceptDefinition>(
  titleConceptCatalog.map((concept) => [concept.id, concept] as const),
);

const titleFamilyById = new Map<string, TitleFamilyDefinition>(
  titleFamilyCatalog.map((family) => [family.id, family] as const),
);

const aliasKindPriority = {
  canonical: 3,
  alias: 2,
  abbreviation: 1,
} as const satisfies Record<TitleAliasDefinition["kind"], number>;

const titleAliasCatalog = titleConceptCatalog
  .flatMap((concept) => {
    const roleGroup = concept.roleGroup ?? roleGroupByFamily.get(concept.family) ?? "engineering";

    return [
      {
        conceptId: concept.id,
        family: concept.family,
        roleGroup,
        canonicalTitle: concept.canonicalTitle,
        kind: "canonical" as const,
        phrase: normalizeTitleText(concept.canonicalTitle),
      },
      ...(concept.aliases ?? []).map((phrase) => ({
        conceptId: concept.id,
        family: concept.family,
        roleGroup,
        canonicalTitle: concept.canonicalTitle,
        kind: "alias" as const,
        phrase: normalizeTitleText(phrase),
      })),
      ...(concept.abbreviations ?? []).map((phrase) => ({
        conceptId: concept.id,
        family: concept.family,
        roleGroup,
        canonicalTitle: concept.canonicalTitle,
        kind: "abbreviation" as const,
        phrase: normalizeTitleText(phrase),
      })),
    ];
  })
  .sort(
    (left, right) =>
      right.phrase.split(" ").length - left.phrase.split(" ").length ||
      right.phrase.length - left.phrase.length ||
      aliasKindPriority[right.kind] - aliasKindPriority[left.kind],
  );

export function listTitleFamilies() {
  return titleFamilyCatalog;
}

export function listTitleConcepts() {
  return titleConceptCatalog;
}

export function getTitleFamily(id?: string) {
  return id ? titleFamilyById.get(id) : undefined;
}

export function getTitleConcept(id?: TitleConceptId) {
  return id ? titleConceptById.get(id) : undefined;
}

export function getTitleFamilyRoleGroup(family?: string): TitleRoleGroup | undefined {
  return family ? roleGroupByFamily.get(family as typeof titleFamilyCatalog[number]["id"]) : undefined;
}

export function findMatchingTitleAliases(value: string) {
  const normalized = normalizeTitleText(value);
  if (!normalized) {
    return [] as TitleAliasDefinition[];
  }

  return titleAliasCatalog.filter((alias) => containsNormalizedPhrase(normalized, alias.phrase));
}

export function areTitleConceptsAdjacent(
  leftConceptId?: TitleConceptId,
  rightConceptId?: TitleConceptId,
) {
  if (!leftConceptId || !rightConceptId || leftConceptId === rightConceptId) {
    return false;
  }

  const left = getTitleConcept(leftConceptId);
  const right = getTitleConcept(rightConceptId);

  return Boolean(
    left?.adjacentConceptIds?.includes(rightConceptId) ||
      right?.adjacentConceptIds?.includes(leftConceptId),
  );
}
